name: build-pdf-cv_resume

on:
  push:

jobs:
  build-pdf:
    name: Build PDF CV Resume
    runs-on: ubuntu-latest
    steps:
      - name: "Set current date as env variable"
        run: |
          echo "builddate=$(date +'%Y')" >> $GITHUB_OUTPUT
        id: version  # this is used on variable path
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run the build process with docker
        uses: addnab/docker-run-action@v3
        with:
          image: yoyonel/pandoc:latest
          options: -v ${{ github.workspace }}:/source
          run: |
            cd /source/pandoc_resume
            make pdf
      - name: rename builds
        run: |
          cp pandoc_resume/resume.pdf "ATTY_Resume-${{ steps.version.outputs.builddate }}.pdf"
	        cp pandoc_resume/references.pdf "ATTY_References-${{ steps.version.outputs.builddate }}.pdf"
      - name: Publishing Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.builddate }}-resume
          name: ${{ steps.version.outputs.builddate }}-resume
          # body: "your date"
          with:
            files: ATTY*.pdf
      # - name: debug - find on current directory
      #   run: find .
